### ISSUE TITLE
Can't join a world. Is this the bug?

### ISSUE THREAD

**Issue by UnexPE** [Nukkit-coders/ASkyBlock-Nukkit#4]
## Nukkit Bug Report  (DO NOT OPEN A ISSUE IF THIS IS A PLUGIN ERROR)  PLUGIN ERROR: TRUE  ### Issue Description  ??  ### Steps to Reproduce the Issue  ??  ### OS and Versions * Nukkit Version: 1.0dev  * Git Commit Abbrev: 96c723d * Java Version:  ``` Java HotSpot(TM) 64-Bit Server VM (1.8.0_161-b12) ```  * Host Configuration:    | Item | Value | |:----:|:-----:| | Host OS | Debian GNU/Linux [8] |   | Memory(RAM) | 8.6 GB |  | Storage Size | 0 B |  | Storage Type |  |  | CPU Type | Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz |  | CPU Core Count | 1 cores 3 threads |  | Upstream Bandwidth | ?? |   * Client Configuration:   | Item | Value | |:----:|:-----:| | Client Edition | ?? |  | Client Version | ?? |   ### Crashdump, Backtrace or Other Files  ``` java.lang.NoSuchMethodError: cn.nukkit.level.format.generic.BaseFullChunk.setBlock(IIILjava/lang/Integer;)Z 	at com.larryTheCoder.SkyBlockGenerator.generateChunk(SkyBlockGenerator.java:68) 	at cn.nukkit.level.generator.task.PopulationTask.onRun(PopulationTask.java:85) 	at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:748)  ```

**Comment by PetteriM1** [comment]
You cant join to server or to skyblock world? I can confirm that this plugin don't work with last NukkitX modifications.

**Comment by UnexPE** [comment]
Did you have a Nukkit Version that works for 1.2.10 and is compatible for Plugin?

**Comment by UnexPE** [comment]
Could you please send the Nukkit version to email unexmc@web.de ?

**Comment by PetteriM1** [comment]
If you mean download link, this is it: [https://9-120112332-gh.circle-artifacts.com/0/tmp/circle-artifacts.LgtG95A/Nukkit-SuomiCraftPE.jar](https://9-120112332-gh.circle-artifacts.com/0/tmp/circle-artifacts.LgtG95A/Nukkit-SuomiCraftPE.jar)
